# Generated by Django 5.0.7 on 2024-11-16 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feelings.feeling')),
            ],
        ),
    ]
